spring.application.name=api

? # Configura��es do banco MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/sesisp
spring.datasource.username=root
spring.datasource.password=root

# Configura��es JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



